/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Hero = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'rarity' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Build = IDL.Record({
  'id' : IDL.Nat,
  'costRare' : IDL.Nat,
  'heroIds' : IDL.Vec(IDL.Nat),
  'authorId' : IDL.Principal,
  'hint' : IDL.Text,
  'requiredSkillIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'costLegendary' : IDL.Nat,
  'costBasic' : IDL.Nat,
  'isPublic' : IDL.Bool,
  'rounds' : IDL.Nat,
  'forbiddenSkillIds' : IDL.Vec(IDL.Nat),
});
export const RecordedBuild = IDL.Record({
  'id' : IDL.Nat,
  'heroId' : IDL.Nat,
  'title' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([Branch], [IDL.Nat], []),
  'addHero' : IDL.Func([Hero], [IDL.Nat], []),
  'addItem' : IDL.Func([Item], [IDL.Nat], []),
  'addSkill' : IDL.Func([Skill], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countPublicBuildsBySkill' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'createBuild' : IDL.Func([Build], [IDL.Nat], []),
  'createRecordedBuild' : IDL.Func([RecordedBuild], [IDL.Nat], []),
  'deleteAllTierLists' : IDL.Func([], [], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'deleteBuildById' : IDL.Func([IDL.Nat], [], []),
  'deleteHero' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteMyTierList' : IDL.Func([], [], []),
  'deleteRecordedBuild' : IDL.Func([IDL.Nat], [], []),
  'deleteSkill' : IDL.Func([IDL.Nat], [], []),
  'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getAllHeroes' : IDL.Func([], [IDL.Vec(Hero)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
  'getMyRecordedBuilds' : IDL.Func([], [IDL.Vec(RecordedBuild)], ['query']),
  'getPublicBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
  'getPublicBuildsExcludingSkills' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Build)],
      ['query'],
    ),
  'getRecordedBuildsByHero' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RecordedBuild)],
      ['query'],
    ),
  'getTierList' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTierList' : IDL.Func([IDL.Text], [], []),
  'seedTestData' : IDL.Func([], [], []),
  'toggleBuildVisibility' : IDL.Func([IDL.Nat], [], []),
  'updateBranch' : IDL.Func([Branch], [], []),
  'updateBuild' : IDL.Func([Build], [], []),
  'updateHero' : IDL.Func([Hero], [], []),
  'updateItem' : IDL.Func([Item], [], []),
  'updateSkill' : IDL.Func([Skill], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Hero = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'rarity' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Build = IDL.Record({
    'id' : IDL.Nat,
    'costRare' : IDL.Nat,
    'heroIds' : IDL.Vec(IDL.Nat),
    'authorId' : IDL.Principal,
    'hint' : IDL.Text,
    'requiredSkillIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'costLegendary' : IDL.Nat,
    'costBasic' : IDL.Nat,
    'isPublic' : IDL.Bool,
    'rounds' : IDL.Nat,
    'forbiddenSkillIds' : IDL.Vec(IDL.Nat),
  });
  const RecordedBuild = IDL.Record({
    'id' : IDL.Nat,
    'heroId' : IDL.Nat,
    'title' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([Branch], [IDL.Nat], []),
    'addHero' : IDL.Func([Hero], [IDL.Nat], []),
    'addItem' : IDL.Func([Item], [IDL.Nat], []),
    'addSkill' : IDL.Func([Skill], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countPublicBuildsBySkill' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'createBuild' : IDL.Func([Build], [IDL.Nat], []),
    'createRecordedBuild' : IDL.Func([RecordedBuild], [IDL.Nat], []),
    'deleteAllTierLists' : IDL.Func([], [], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'deleteBuildById' : IDL.Func([IDL.Nat], [], []),
    'deleteHero' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteMyTierList' : IDL.Func([], [], []),
    'deleteRecordedBuild' : IDL.Func([IDL.Nat], [], []),
    'deleteSkill' : IDL.Func([IDL.Nat], [], []),
    'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getAllHeroes' : IDL.Func([], [IDL.Vec(Hero)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
    'getMyRecordedBuilds' : IDL.Func([], [IDL.Vec(RecordedBuild)], ['query']),
    'getPublicBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
    'getPublicBuildsExcludingSkills' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Build)],
        ['query'],
      ),
    'getRecordedBuildsByHero' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RecordedBuild)],
        ['query'],
      ),
    'getTierList' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTierList' : IDL.Func([IDL.Text], [], []),
    'seedTestData' : IDL.Func([], [], []),
    'toggleBuildVisibility' : IDL.Func([IDL.Nat], [], []),
    'updateBranch' : IDL.Func([Branch], [], []),
    'updateBuild' : IDL.Func([Build], [], []),
    'updateHero' : IDL.Func([Hero], [], []),
    'updateItem' : IDL.Func([Item], [], []),
    'updateSkill' : IDL.Func([Skill], [], []),
  });
};

export const init = ({ IDL }) => { return []; };