/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branch { 'id' : bigint, 'name' : string, 'imageUrl' : string }
export interface Build {
  'id' : bigint,
  'costRare' : bigint,
  'heroIds' : Array<bigint>,
  'authorId' : Principal,
  'hint' : string,
  'requiredSkillIds' : Array<bigint>,
  'name' : string,
  'createdAt' : bigint,
  'costLegendary' : bigint,
  'costBasic' : bigint,
  'isPublic' : boolean,
  'rounds' : bigint,
  'forbiddenSkillIds' : Array<bigint>,
}
export interface Hero {
  'id' : bigint,
  'name' : string,
  'tier' : string,
  'imageUrl' : string,
}
export interface Item { 'id' : bigint, 'name' : string, 'imageUrl' : string }
export interface RecordedBuild {
  'id' : bigint,
  'heroId' : bigint,
  'title' : string,
  'authorId' : Principal,
  'createdAt' : bigint,
}
export interface Skill {
  'id' : bigint,
  'name' : string,
  'imageUrl' : string,
  'rarity' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Branch CRUD (admin-only)
   */
  'addBranch' : ActorMethod<[Branch], bigint>,
  /**
   * / Hero CRUD (admin-only)
   */
  'addHero' : ActorMethod<[Hero], bigint>,
  /**
   * / Item CRUD (admin-only)
   */
  'addItem' : ActorMethod<[Item], bigint>,
  /**
   * / Skill CRUD (admin-only)
   */
  'addSkill' : ActorMethod<[Skill], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countPublicBuildsBySkill' : ActorMethod<[bigint], bigint>,
  /**
   * / Builds (user CRUD, admins manage all)
   */
  'createBuild' : ActorMethod<[Build], bigint>,
  /**
   * / Recorded builds
   */
  'createRecordedBuild' : ActorMethod<[RecordedBuild], bigint>,
  'deleteAllTierLists' : ActorMethod<[], undefined>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'deleteBuildById' : ActorMethod<[bigint], undefined>,
  'deleteHero' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteMyTierList' : ActorMethod<[], undefined>,
  'deleteRecordedBuild' : ActorMethod<[bigint], undefined>,
  'deleteSkill' : ActorMethod<[bigint], undefined>,
  'getAllBranches' : ActorMethod<[], Array<Branch>>,
  'getAllHeroes' : ActorMethod<[], Array<Hero>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllSkills' : ActorMethod<[], Array<Skill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBuilds' : ActorMethod<[], Array<Build>>,
  'getMyRecordedBuilds' : ActorMethod<[], Array<RecordedBuild>>,
  'getPublicBuilds' : ActorMethod<[], Array<Build>>,
  'getPublicBuildsExcludingSkills' : ActorMethod<[Array<bigint>], Array<Build>>,
  'getRecordedBuildsByHero' : ActorMethod<[bigint], Array<RecordedBuild>>,
  'getTierList' : ActorMethod<[Principal], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Tier list management
   */
  'saveTierList' : ActorMethod<[string], undefined>,
  /**
   * / Seed initial test data
   */
  'seedTestData' : ActorMethod<[], undefined>,
  'toggleBuildVisibility' : ActorMethod<[bigint], undefined>,
  'updateBranch' : ActorMethod<[Branch], undefined>,
  'updateBuild' : ActorMethod<[Build], undefined>,
  'updateHero' : ActorMethod<[Hero], undefined>,
  'updateItem' : ActorMethod<[Item], undefined>,
  'updateSkill' : ActorMethod<[Skill], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];