/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Hero {
    id: bigint;
    name: string;
    tier: string;
    imageUrl: string;
}
export interface Build {
    id: bigint;
    costRare: bigint;
    heroIds: Array<bigint>;
    authorId: Principal;
    hint: string;
    requiredSkillIds: Array<bigint>;
    name: string;
    createdAt: bigint;
    costLegendary: bigint;
    costBasic: bigint;
    isPublic: boolean;
    rounds: bigint;
    forbiddenSkillIds: Array<bigint>;
}
export interface Item {
    id: bigint;
    name: string;
    imageUrl: string;
}
export interface Skill {
    id: bigint;
    name: string;
    imageUrl: string;
    rarity: string;
}
export interface Branch {
    id: bigint;
    name: string;
    imageUrl: string;
}
export interface RecordedBuild {
    id: bigint;
    heroId: bigint;
    title: string;
    authorId: Principal;
    createdAt: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Branch CRUD (admin-only)
     */
    addBranch(branch: Branch): Promise<bigint>;
    /**
     * / Hero CRUD (admin-only)
     */
    addHero(hero: Hero): Promise<bigint>;
    /**
     * / Item CRUD (admin-only)
     */
    addItem(item: Item): Promise<bigint>;
    /**
     * / Skill CRUD (admin-only)
     */
    addSkill(skill: Skill): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    countPublicBuildsBySkill(skillId: bigint): Promise<bigint>;
    /**
     * / Builds (user CRUD, admins manage all)
     */
    createBuild(newBuild: Build): Promise<bigint>;
    /**
     * / Recorded builds
     */
    createRecordedBuild(recordedBuild: RecordedBuild): Promise<bigint>;
    deleteAllTierLists(): Promise<void>;
    deleteBranch(branchId: bigint): Promise<void>;
    deleteBuildById(buildId: bigint): Promise<void>;
    deleteHero(heroId: bigint): Promise<void>;
    deleteItem(itemId: bigint): Promise<void>;
    deleteMyTierList(): Promise<void>;
    deleteRecordedBuild(recordedBuildId: bigint): Promise<void>;
    deleteSkill(skillId: bigint): Promise<void>;
    getAllBranches(): Promise<Array<Branch>>;
    getAllHeroes(): Promise<Array<Hero>>;
    getAllItems(): Promise<Array<Item>>;
    getAllSkills(): Promise<Array<Skill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBuilds(): Promise<Array<Build>>;
    getMyRecordedBuilds(): Promise<Array<RecordedBuild>>;
    getPublicBuilds(): Promise<Array<Build>>;
    getPublicBuildsExcludingSkills(excludedSkillIds: Array<bigint>): Promise<Array<Build>>;
    getRecordedBuildsByHero(heroId: bigint): Promise<Array<RecordedBuild>>;
    getTierList(userId: Principal): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Tier list management
     */
    saveTierList(data: string): Promise<void>;
    /**
     * / Seed initial test data
     */
    seedTestData(): Promise<void>;
    toggleBuildVisibility(buildId: bigint): Promise<void>;
    updateBranch(updatedBranch: Branch): Promise<void>;
    updateBuild(build: Build): Promise<void>;
    updateHero(updatedHero: Hero): Promise<void>;
    updateItem(updatedItem: Item): Promise<void>;
    updateSkill(updatedSkill: Skill): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBranch(arg0: Branch): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBranch(arg0);
            return result;
        }
    }
    async addHero(arg0: Hero): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHero(arg0);
            return result;
        }
    }
    async addItem(arg0: Item): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0);
            return result;
        }
    }
    async addSkill(arg0: Skill): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async countPublicBuildsBySkill(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countPublicBuildsBySkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countPublicBuildsBySkill(arg0);
            return result;
        }
    }
    async createBuild(arg0: Build): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuild(arg0);
            return result;
        }
    }
    async createRecordedBuild(arg0: RecordedBuild): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecordedBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecordedBuild(arg0);
            return result;
        }
    }
    async deleteAllTierLists(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllTierLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllTierLists();
            return result;
        }
    }
    async deleteBranch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteBuildById(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBuildById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBuildById(arg0);
            return result;
        }
    }
    async deleteHero(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHero(arg0);
            return result;
        }
    }
    async deleteItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteMyTierList(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyTierList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyTierList();
            return result;
        }
    }
    async deleteRecordedBuild(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecordedBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecordedBuild(arg0);
            return result;
        }
    }
    async deleteSkill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkill(arg0);
            return result;
        }
    }
    async getAllBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBranches();
            return result;
        }
    }
    async getAllHeroes(): Promise<Array<Hero>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHeroes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHeroes();
            return result;
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return result;
        }
    }
    async getAllSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSkills();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBuilds(): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBuilds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBuilds();
            return result;
        }
    }
    async getMyRecordedBuilds(): Promise<Array<RecordedBuild>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecordedBuilds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecordedBuilds();
            return result;
        }
    }
    async getPublicBuilds(): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicBuilds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicBuilds();
            return result;
        }
    }
    async getPublicBuildsExcludingSkills(arg0: Array<bigint>): Promise<Array<Build>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicBuildsExcludingSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicBuildsExcludingSkills(arg0);
            return result;
        }
    }
    async getRecordedBuildsByHero(arg0: bigint): Promise<Array<RecordedBuild>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordedBuildsByHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordedBuildsByHero(arg0);
            return result;
        }
    }
    async getTierList(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierList(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierList(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTierList(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTierList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTierList(arg0);
            return result;
        }
    }
    async seedTestData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTestData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTestData();
            return result;
        }
    }
    async toggleBuildVisibility(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBuildVisibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBuildVisibility(arg0);
            return result;
        }
    }
    async updateBranch(arg0: Branch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0);
            return result;
        }
    }
    async updateBuild(arg0: Build): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBuild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBuild(arg0);
            return result;
        }
    }
    async updateHero(arg0: Hero): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHero(arg0);
            return result;
        }
    }
    async updateItem(arg0: Item): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0);
            return result;
        }
    }
    async updateSkill(arg0: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkill(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string, arg1: string): Promise<bigint> {
        const result = await (this.actor as any).sendChatMessage(arg0, arg1);
        return result;
    }
    async getChatMessages(): Promise<Array<any>> {
        const result = await (this.actor as any).getChatMessages();
        return result;
    }
    async onlineHeartbeat(arg0: string): Promise<bigint> {
        const result = await (this.actor as any).onlineHeartbeat(arg0);
        return result;
    }
    async getOnlineUsers(): Promise<Array<any>> {
        const result = await (this.actor as any).getOnlineUsers();
        return result;
    }
    async getAllRegisteredUsers(): Promise<Array<any>> {
        const result = await (this.actor as any).getAllRegisteredUsers();
        return result;
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
